# Generated by Django 3.2.8 on 2022-08-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('rank', models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='S', max_length=20, verbose_name='Rank')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heros',
                'ordering': ['created_at'],
            },
        ),
    ]
