version: "3.1"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - /mnt/data:/db
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iheros

  adminer:
    image: adminer
    restart: always
    ports:
      - 8060:8080
