# Generated by Django 3.2.8 on 2022-08-17 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
        ('threat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threat',
            name='defeated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='hero.hero', verbose_name='defeated_by'),
        ),
        migrations.AlterField(
            model_name='threat',
            name='location',
            field=models.JSONField(verbose_name='Location coordinates'),
        ),
    ]
