# Generated by Django 3.2.8 on 2022-08-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat', '0002_auto_20220817_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threat',
            name='danger_level',
            field=models.CharField(choices=[('God', 'God'), ('Dragon', 'Dragon'), ('Tiger', 'Tiger'), ('Wolf', 'Wolf')], default='Wolf', max_length=30, verbose_name='DangerLevel'),
        ),
    ]
